# OWLWATCH Daily (AM + PM)
# GitHub Actions cron uses UTC.

name: OWLWATCH Daily (AM + PM)

on:
  schedule:
    - cron: "0 14 * * *"   # 14:00 UTC => 08:00 CT
    - cron: "0 4 * * *"    # 04:00 UTC => 22:00 CT (previous day / next day mapping)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  owlwatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Determine run slot (AM/PM) based on scheduled UTC hour
        id: slot
        run: |
          HOUR_UTC=$(date -u +%H)
          if [ "$HOUR_UTC" = "14" ]; then
            echo "slot=AM" >> $GITHUB_OUTPUT
          elif [ "$HOUR_UTC" = "04" ] || [ "$HOUR_UTC" = "4" ]; then
            echo "slot=PM" >> $GITHUB_OUTPUT
          else
            # For manual runs, default AM unless overridden by input env
            echo "slot=AM" >> $GITHUB_OUTPUT
          fi

      - name: Run OWLWATCH generator + Discord post
        env:
          OWLWATCH_TZ: "America/Chicago"
          OWLWATCH_RUN_SLOT: ${{ steps.slot.outputs.slot }}
          OWLWATCH_TITLE: "KEYSGUARD OWLWATCH — Daily Cyber Intelligence Brief"
          OWLWATCH_WEBHOOK_URL: ${{ secrets.OWLWATCH_DISCORD_WEBHOOK }}
          OWLWATCH_OUTPUT_DIR: "output"
          OWLWATCH_STATE_DIR: "state"
        run: |
          python owlwatch_report.py

      - name: Commit generated artifacts (optional but recommended)
        run: |
          git config user.name "owlwatch-bot"
          git config user.email "owlwatch-bot@users.noreply.github.com"
          git add output state || true
          git commit -m "OWLWATCH: update artifacts" || echo "No changes to commit"
          git push